<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IframeLink</name>
   <tag></tag>
   <elementGuidId>3ecc6fec-c045-43e5-866f-51371cd2fc9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img_ad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='aw0']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc6fadae-70b4-40ff-bc4d-4e92ec878615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://tpc.googlesyndication.com/simgad/14568351763690867874</value>
      <webElementGuid>815df6c9-01bf-4bfd-99c8-075ca64cda1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af236013-3133-4471-9922-8bbb97877264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>524fc5f3-430a-405a-a6ff-d6a00ab99a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>0fa62678-76af-4981-9dd7-79a977c71e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_ad</value>
      <webElementGuid>25c08e90-dc84-4605-9e44-ffcce7731016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aw0&quot;)/img[@class=&quot;img_ad&quot;]</value>
      <webElementGuid>7d1ee290-1b8e-4418-8192-a23b7200448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/IframeLocators/Iframe</value>
      <webElementGuid>01570efc-4e3e-494f-9606-ce352e2482c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='aw0']/img</value>
      <webElementGuid>f1d39382-f112-43a2-8631-d5b570f63caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://tpc.googlesyndication.com/simgad/14568351763690867874')]</value>
      <webElementGuid>74a1c714-4b5d-46ae-888f-348d53ce6820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8768ca05-9106-43d9-a5fe-84a38ce157f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://tpc.googlesyndication.com/simgad/14568351763690867874']</value>
      <webElementGuid>4b6a3ee4-95bb-43a7-8240-99a5a6edd80b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
