<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_W3.CSS Downloads_google_ads_iframe_22152718,16833175sws-hbw3schools.commain_leaderboard_0</name>
   <tag></tag>
   <elementGuidId>dcf9f01e-da96-4700-9f6e-2c5926ba29e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;google_ads_iframe_\/22152718\,16833175\/sws-hb\/\/w3schools\.com\/\/main_leaderboard_0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f42bdb5d-edf3-472b-918c-52a1b8c3f004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0</value>
      <webElementGuid>81ccaeb5-27e1-4ade-8149-8bd2a59d6373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0</value>
      <webElementGuid>1cd595be-b81d-4dd0-81a2-0d6b769c9066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>b439dee7-4888-4604-9f27-1eb9adb8ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>9dbd8f1a-a2ec-4706-90e9-61c9e6be1407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>7a1df570-b43a-4ffc-93ed-8d478460b424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>befbe06f-43e7-4bfc-ad61-522eb8c2f8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25a986d0-2346-47bf-810a-bae03f3b8274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2456e88-602f-43dd-8f61-6ac3f8541478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>078ea996-3e06-4876-8be4-77908b001585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>62dfb65c-b9e0-4f3c-9cf7-a9406c7048eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3efcedd6-11a8-4379-aa83-982c3b89bc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>private-state-token-redemption;attribution-reporting</value>
      <webElementGuid>c4a32d42-3bb0-4335-a2d9-e7ec34ea4e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>82e7eae7-e9d4-44b5-915d-7c3eff979900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4aee188b-aa41-49b0-91e3-ab7a1db6dd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0&quot;)</value>
      <webElementGuid>5e13bcf6-bcc1-48d0-a8bd-1ed0aa5d171c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0']</value>
      <webElementGuid>de74326d-62a0-40d1-8152-8f89f0517bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0__container__']/iframe</value>
      <webElementGuid>386cfdeb-7db4-485e-8b60-085c8d176b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5a6866d0-f193-40d6-a674-b09a0ff1fced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0' and @name = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//main_leaderboard_0' and @title = '3rd party ad content']</value>
      <webElementGuid>2d6c64fd-508b-49fb-a75f-edf99202b008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
