<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , aw0, , )imgclass, , img_ad, , )_img_ad</name>
   <tag></tag>
   <elementGuidId>69b31f83-1a3a-461c-871a-e4ed36a0eab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img_ad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='aw0']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3052df2-2da3-411a-a4ae-28395af4b1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://tpc.googlesyndication.com/simgad/14568351763690867874</value>
      <webElementGuid>70481900-db62-4546-9008-2d8752ffc645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>396ce478-0cd5-4828-a8cc-e10dd55103d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>1a0bcc9e-6a0b-4d43-ac0e-6a69f32f4ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>91fcb19b-6241-4fa8-b76b-4157d6d43921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_ad</value>
      <webElementGuid>e59effeb-a5dd-444b-b7cf-c4123f2a59fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aw0&quot;)/img[@class=&quot;img_ad&quot;]</value>
      <webElementGuid>e0ed18b6-8af4-4792-8c98-d30ad338b3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/IframeSpy/Page_W3.CSS Templates/iframe_W3.CSS Downloads_google_ads_iframe_22152718,16833175sws-hbw3schools.commain_leaderboard_0</value>
      <webElementGuid>237c8769-38df-4946-8fec-12e45f27e7dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='aw0']/img</value>
      <webElementGuid>6e0d2292-4b1e-4b10-90fe-a48f75c875bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://tpc.googlesyndication.com/simgad/14568351763690867874')]</value>
      <webElementGuid>8c6f5458-a978-4290-97ce-811ad88e19c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fc445fc0-0d94-4ae9-ae33-5c088e0c7131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://tpc.googlesyndication.com/simgad/14568351763690867874']</value>
      <webElementGuid>b79818bf-deb2-4c73-9af4-3aa9721f8259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
